# Generated by Django 3.2.3 on 2021-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testupload',
            name='file',
            field=models.FileField(upload_to='core'),
        ),
    ]
